package com.yih.chasm;

import com.yih.chasm.config.Config;
import com.yih.chasm.service.StorageProxy;
import com.yih.chasm.sql.ContentService;
import com.yih.chasm.storage.StorageService;
import com.yih.chasm.util.ThreadManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Site0 {
    public static void main(String[] args) throws InterruptedException {

        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {

            }
        });

        ThreadManager.instance().submit(StorageService.instance());

        Config c = new Config();
        c.read();
        System.out.println(c.getEndPoints());
        System.out.println(c.getPort());


        StorageProxy sp = new StorageProxy(c);
        sp.run();
        Thread.sleep(5000);
        for (int i = 0; i < 10; i++) {
            String cmd = String.format("set key-%d value-%d", i, i);
            sp.beginPaxos(i, "abcdefghijklmnoperestuvwxya" +i, cmd);
//            Thread.sleep(1000);
        }
        StorageService.instance().debugPrint();
        ContentService.instance().debug();
    }
}