package com.yih.chasm;

import com.yih.chasm.config.Config;
import com.yih.chasm.service.StorageProxy;
import com.yih.chasm.storage.MetaService;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Site0 {
    public static void main(String[] args) throws InterruptedException {

        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {
                MetaService.write();
            }
        });

        Config c = new Config();
        c.read();
        System.out.println(c.getEndPoints());
        System.out.println(c.getPort());


        StorageProxy sp = new StorageProxy(c);
        sp.run();
        Thread.sleep(5000);
        sp.beginPaxos(1, "a", "test");
        sp.beginPaxos(2, "a", "ggg");
        sp.beginPaxos(3, "a", "jfkls");
        sp.beginPaxos(2, "a", "jk");
        for (int i = 0; i < 100; i++) {
            sp.beginPaxos(5, "a", "jk");
        }
        MetaService.instance().print();

    }
}