package com.yih.chasm;

import com.yih.chasm.config.Config;
import com.yih.chasm.transport.Client;
import com.yih.chasm.transport.Server;

import java.net.InetSocketAddress;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws InterruptedException {
        System.out.println(new App().getGreeting());
        Config c = new Config();
        c.read();
        System.out.println(c.getEndPoints());

        Thread server = new Thread(new Server());
        server.start();
        System.out.println("server");
        Client c1 = new Client();
        Thread client = new Thread(c1);
        client.start();
        System.out.println("ok");
        Thread.sleep(5000);
        c1.test(InetSocketAddress.createUnresolved("localhost/127.0.0.1", 12345));

    }

    public String getGreeting() {
        return "Hello world.";
    }
}