package com.yih.chasm;

import com.yih.chasm.net.Server;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Server server = new Server();
        server.start();
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
